apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ssdb
spec:
  serviceName: ssdb
  replicas: 3
  selector:
    matchLabels:
      app: ssdb
  template:
    metadata:
      labels:
        app: ssdb
    spec:
      containers:
      - name: ssdb
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
              secretKeyRef:
                   name: ssdb-secret
                   key: root_pw
